### model
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
trust_remote_code: true
replace_lm_head: true  # Replace lm_head with AcceptHead (2-layer MLP)

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_target: all
additional_target: lm_head  # 使 AcceptHead 可训练（直接训练 AcceptHead 的所有参数，而不是添加 LoRA 适配器）

### dataset
dataset: accept_head
template: llama3
cutoff_len: 4096
max_samples: null
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4
use_accept_head_format: true  # Enable AcceptHead dataset format

### output
output_dir: saves/llama3.1-8b/sft/default
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]
run_name: default

### train
per_device_train_batch_size: 64
gradient_accumulation_steps: 1
learning_rate: 1.0e-3
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
val_size: 0.01  # 分出5%的数据作为验证集
per_device_eval_batch_size: 64
eval_strategy: steps  # 按步数进行评估
eval_steps: 250  # 每250步进行一次评估（可以根据需要调整）
compute_accuracy: true  # 启用accuracy计算
accept_head_accuracy_tolerance: 0.2  # Accuracy容差阈值（0.1表示10%的相对误差）

